/* Generated By:JavaCC: Do not edit this line. GramaticaJCC.java */
package Arit.AnalizadorJCC;
import Arit.AltaAbstraccion.*;
import Arit.CambioFlujo.*;
import Arit.Ciclos.*;
import Arit.ControlDeFlujo.*;
import Arit.Entorno.*;
import Arit.OperacionersPrimitivas.*;
import Arit.ValorImplicito.*;
import Error.ErrorAr;
import Informacion.Informacion;

import java.util.LinkedList;

public class GramaticaJCC implements GramaticaJCCConstants {

    public void error_skipto(int kind) {
        ParseException e = generateParseException();  // generate the exception object.
        System.out.println(e.toString());  // print the error message
        Token t;
        //Informacion.agregarError( new ErrorAr("Sintactico", "No se esperaba '" + n +"'", fila,  columna ));
        do {
          t = getNextToken();
        } while (t.kind != kind);
    }

  final public LinkedList<NodoAst> Inicio() throws ParseException {
    LinkedList<NodoAst> Ast = new LinkedList<NodoAst>();
    Ast = Campos();
    jj_consume_token(0);
                           {if (true) return Ast;}
    throw new Error("Missing return statement in function");
  }

  final public LinkedList<NodoAst> Campos() throws ParseException {
    NodoAst ins;
    LinkedList<NodoAst> lista = new LinkedList<NodoAst>();
    label_1:
    while (true) {
      ins = Campo();
                      lista.add(ins);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPRIMIR:
      case SI:
      case SWITCH:
      case WHILE:
      case BREAK:
      case CONTINUE:
      case RETURN:
      case DO:
      case FOR:
      case IDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
      {if (true) return lista;}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Campo() throws ParseException {
    NodoAst sen;
    try {
      if (jj_2_1(5)) {
        sen = DeclararFuncion();
                                                         {if (true) return sen;}
      } else if (jj_2_2(3)) {
        sen = Declaracion();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PTCOMA:
          jj_consume_token(PTCOMA);
          break;
        default:
          jj_la1[1] = jj_gen;
          ;
        }
                                                             {if (true) return sen;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IMPRIMIR:
          sen = Imprimir();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[2] = jj_gen;
            ;
          }
                                              {if (true) return sen;}
          break;
        case SI:
          sen = Si();
                                              {if (true) return sen;}
          break;
        case SWITCH:
          sen = Seleccionar();
                                              {if (true) return sen;}
          break;
        case WHILE:
          sen = While();
                                              {if (true) return sen;}
          break;
        case DO:
          sen = DoWhile();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[3] = jj_gen;
            ;
          }
                                              {if (true) return sen;}
          break;
        case FOR:
          sen = For();
                                              {if (true) return sen;}
          break;
        case BREAK:
          sen = Break();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[4] = jj_gen;
            ;
          }
                                              {if (true) return sen;}
          break;
        case CONTINUE:
          sen = Continue();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[5] = jj_gen;
            ;
          }
                                              {if (true) return sen;}
          break;
        case RETURN:
          sen = Return();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[6] = jj_gen;
            ;
          }
                                              {if (true) return sen;}
          break;
        default:
          jj_la1[9] = jj_gen;
          if (jj_2_3(3)) {
            sen = Llamada();
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case PTCOMA:
              jj_consume_token(PTCOMA);
              break;
            default:
              jj_la1[7] = jj_gen;
              ;
            }
                                                            {if (true) return sen;}
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case IDENTIFICADOR:
              sen = AsignarEstructura();
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case PTCOMA:
                jj_consume_token(PTCOMA);
                break;
              default:
                jj_la1[8] = jj_gen;
                ;
              }
                                                      {if (true) return sen;}
              break;
            default:
              jj_la1[10] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    } catch (ParseException e) {
            Informacion.agregarError( new ErrorAr("Sintactico", e.getMessage(),  e.currentToken.beginLine, e.currentToken.beginColumn ));
            Token t;
            System.out.println(e.toString());
            do {
                t = getNextToken();
            } while (t.kind != PTCOMA && t!=null && t.kind != EOF );
            {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoAst DeclararFuncion() throws ParseException {
    Token t;
    LinkedList<Parametro> parametros =  new LinkedList<Parametro>();
    LinkedList<NodoAst> sentencias;
    if (jj_2_4(3)) {
      t = jj_consume_token(IDENTIFICADOR);
      jj_consume_token(IGUAL);
      jj_consume_token(FUNCTION);
      jj_consume_token(PARA);
      parametros = Parametros();
      jj_consume_token(PARC);
      jj_consume_token(LLAVEA);
      sentencias = Sentencias();
      jj_consume_token(LLAVEC);
      {if (true) return new Funcion(t.image, parametros, sentencias, token.beginLine, token.beginColumn);}
    } else if (jj_2_5(3)) {
      t = jj_consume_token(IDENTIFICADOR);
      jj_consume_token(IGUAL);
      jj_consume_token(PARA);
      parametros = Parametros();
      jj_consume_token(PARC);
      jj_consume_token(FLECHA);
      jj_consume_token(LLAVEA);
      sentencias = Sentencias();
      jj_consume_token(LLAVEC);
      {if (true) return new Funcion(t.image, parametros, sentencias, token.beginLine, token.beginColumn);}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public LinkedList<Parametro> Parametros() throws ParseException {
    LinkedList<Parametro> parametros =  new LinkedList<Parametro>();
    Parametro par;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      par = Parametro();
                         parametros.add(par);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMA:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_2;
        }
        jj_consume_token(COMA);
        par = Parametro();
                                                                             parametros.add(par);
      }
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
      {if (true) return parametros;}
    throw new Error("Missing return statement in function");
  }

  final public Parametro Parametro() throws ParseException {
    Token t;
    Expresion def = null;
    t = jj_consume_token(IDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IGUAL:
      jj_consume_token(IGUAL);
      def = Expresion();
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
      {if (true) return new Parametro(t.image, def);}
    throw new Error("Missing return statement in function");
  }

  final public LinkedList<NodoAst> Sentencias() throws ParseException {
    LinkedList<NodoAst> sentencias = new LinkedList<NodoAst>();
    NodoAst sentencia;
    label_3:
    while (true) {
      sentencia = Sentencia();
                                sentencias.add(sentencia);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPRIMIR:
      case SI:
      case SWITCH:
      case WHILE:
      case BREAK:
      case CONTINUE:
      case RETURN:
      case DO:
      case FOR:
      case IDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_3;
      }
    }
      {if (true) return sentencias;}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Sentencia() throws ParseException {
    NodoAst sen;
    try {
      if (jj_2_6(3)) {
        sen = Declaracion();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PTCOMA:
          jj_consume_token(PTCOMA);
          break;
        default:
          jj_la1[15] = jj_gen;
          ;
        }
                                                      {if (true) return sen;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IMPRIMIR:
          sen = Imprimir();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[16] = jj_gen;
            ;
          }
                                                      {if (true) return sen;}
          break;
        case SI:
          sen = Si();
                                                      {if (true) return sen;}
          break;
        case SWITCH:
          sen = Seleccionar();
                                                      {if (true) return sen;}
          break;
        case WHILE:
          sen = While();
                                                      {if (true) return sen;}
          break;
        case DO:
          sen = DoWhile();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[17] = jj_gen;
            ;
          }
                                                      {if (true) return sen;}
          break;
        case FOR:
          sen = For();
                                                      {if (true) return sen;}
          break;
        case BREAK:
          sen = Break();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[18] = jj_gen;
            ;
          }
                                                      {if (true) return sen;}
          break;
        case CONTINUE:
          sen = Continue();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[19] = jj_gen;
            ;
          }
                                                      {if (true) return sen;}
          break;
        case RETURN:
          sen = Return();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PTCOMA:
            jj_consume_token(PTCOMA);
            break;
          default:
            jj_la1[20] = jj_gen;
            ;
          }
                                                      {if (true) return sen;}
          break;
        default:
          jj_la1[23] = jj_gen;
          if (jj_2_7(3)) {
            sen = Llamada();
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case PTCOMA:
              jj_consume_token(PTCOMA);
              break;
            default:
              jj_la1[21] = jj_gen;
              ;
            }
                                                                   {if (true) return sen;}
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case IDENTIFICADOR:
              sen = AsignarEstructura();
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case PTCOMA:
                jj_consume_token(PTCOMA);
                break;
              default:
                jj_la1[22] = jj_gen;
                ;
              }
                                                      {if (true) return sen;}
              break;
            default:
              jj_la1[24] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    } catch (ParseException e) {
        Token t;
        Informacion.agregarError( new ErrorAr("Sintactico", e.getMessage(),  e.currentToken.beginLine, e.currentToken.beginColumn ));
        System.out.println(e.toString());
        do {
            t = getNextToken();
        } while (t.kind != PTCOMA && t!=null && t.kind != EOF );
        {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Declaracion() throws ParseException {
    NodoAst ins;
    Expresion e;
    Token t;
    t = jj_consume_token(IDENTIFICADOR);
    jj_consume_token(IGUAL);
    e = Expresion();
                                                          ins =  new DeclaracionAsignacion(t.image, e, token.beginLine, token.beginColumn);
      {if (true) return ins;}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Imprimir() throws ParseException {
    NodoAst ins;
    Expresion e;
    jj_consume_token(IMPRIMIR);
    jj_consume_token(PARA);
    e = Expresion();
    jj_consume_token(PARC);
                                                     ins = new Imprimir(e, token.beginLine, token.beginColumn);
      {if (true) return ins;}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Si() throws ParseException {
    Expresion cond;
    LinkedList<NodoAst> sentencias;
    NodoAst ifElse;
    LinkedList<NodoAst> sentenciasElse = null;
    jj_consume_token(SI);
    jj_consume_token(PARA);
    cond = Expresion();
    jj_consume_token(PARC);
    jj_consume_token(LLAVEA);
    sentencias = Sentencias();
    jj_consume_token(LLAVEC);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINO:
      if (jj_2_8(2)) {
        jj_consume_token(SINO);
        ifElse = Si();
                                                         sentenciasElse = new LinkedList<NodoAst>(); sentenciasElse.add(ifElse);
      } else if (jj_2_9(2)) {
        jj_consume_token(SINO);
        jj_consume_token(LLAVEA);
        sentenciasElse = Sentencias();
        jj_consume_token(LLAVEC);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }
      {if (true) return new Si(cond, sentencias, sentenciasElse, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Seleccionar() throws ParseException {
    Expresion cond;
    LinkedList<Caso> casos;
    Caso defecto = null;
    LinkedList<NodoAst> sentenciasDefault = null;
    jj_consume_token(SWITCH);
    jj_consume_token(PARA);
    cond = Expresion();
    jj_consume_token(PARC);
    jj_consume_token(LLAVEA);
    casos = Casos();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEFECTO:
      jj_consume_token(DEFECTO);
      jj_consume_token(DOSPUNTOS);
      sentenciasDefault = Sentencias();
                                                               defecto = new Caso(null, sentenciasDefault);
      break;
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    jj_consume_token(LLAVEC);
      {if (true) return new Seleccionar(cond, casos, defecto, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public LinkedList<Caso> Casos() throws ParseException {
    Expresion cond;
    LinkedList<Caso> casos = new LinkedList<Caso>();
    LinkedList<NodoAst> sentencias;
    label_4:
    while (true) {
      jj_consume_token(CASE);
      cond = Expresion();
      jj_consume_token(DOSPUNTOS);
      sentencias = Sentencias();
                                                                        casos.add(new Caso(cond, sentencias));
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CASE:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_4;
      }
    }
      {if (true) return casos;}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst While() throws ParseException {
    Expresion condicion;
    LinkedList<NodoAst> sentencias;
    jj_consume_token(WHILE);
    jj_consume_token(PARA);
    condicion = Expresion();
    jj_consume_token(PARC);
    jj_consume_token(LLAVEA);
    sentencias = Sentencias();
    jj_consume_token(LLAVEC);
      {if (true) return new While(condicion, sentencias, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst DoWhile() throws ParseException {
    Expresion condicion;
    LinkedList<NodoAst> sentencias;
    jj_consume_token(DO);
    jj_consume_token(LLAVEA);
    sentencias = Sentencias();
    jj_consume_token(LLAVEC);
    jj_consume_token(WHILE);
    jj_consume_token(PARA);
    condicion = Expresion();
    jj_consume_token(PARC);
      {if (true) return new DoWhile(condicion, sentencias, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst For() throws ParseException {
    Token t;
    Expresion estructura;
    LinkedList<NodoAst> sentencias;
    jj_consume_token(FOR);
    jj_consume_token(PARA);
    t = jj_consume_token(IDENTIFICADOR);
    jj_consume_token(IN);
    estructura = Expresion();
    jj_consume_token(PARC);
    jj_consume_token(LLAVEA);
    sentencias = Sentencias();
    jj_consume_token(LLAVEC);
      {if (true) return new For(t.image, estructura, sentencias, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Break() throws ParseException {
    jj_consume_token(BREAK);
      {if (true) return new Break(token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Continue() throws ParseException {
    jj_consume_token(CONTINUE);
      {if (true) return new Continue(token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public NodoAst Return() throws ParseException {
    Expresion ret = null;
    jj_consume_token(RETURN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PARA:
      jj_consume_token(PARA);
      ret = Expresion();
      jj_consume_token(PARC);
      break;
    default:
      jj_la1[28] = jj_gen;
      ;
    }
      {if (true) return new Return(ret, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public Expresion Llamada() throws ParseException {
    Token t;
    LinkedList<Expresion> valores = new LinkedList<Expresion>();
    Expresion e;
    LinkedList<NodoAcceso> accesos;
    t = jj_consume_token(IDENTIFICADOR);
    jj_consume_token(PARA);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ENTERO:
    case DECIMAL:
    case TRUE:
    case FALSE:
    case NULO:
    case DEFECTO:
    case PARA:
    case MENOS:
    case NOT:
    case IDENTIFICADOR:
    case STRING:
      e = Expresion();
                                                   valores.add(e);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMA:
          ;
          break;
        default:
          jj_la1[29] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMA);
        e = Expresion();
                                                                                                valores.add(e);
      }
      break;
    default:
      jj_la1[30] = jj_gen;
      ;
    }
    jj_consume_token(PARC);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BRAA:
      accesos = Accesos();
                           {if (true) return new LlamadaAcceso( new Llamada(t.image, valores, token.beginLine, token.beginColumn), accesos, token.beginLine, token.beginColumn);}
      break;
    default:
      jj_la1[31] = jj_gen;
      ;
    }
      {if (true) return new Llamada(t.image, valores, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public Expresion Acceso() throws ParseException {
    Token t;
    LinkedList<NodoAcceso> accesos;
    t = jj_consume_token(IDENTIFICADOR);
    accesos = Accesos();
      {if (true) return new Acceso(t.image, accesos, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public LinkedList<NodoAcceso> Accesos() throws ParseException {
    LinkedList<NodoAcceso> accesos = new LinkedList<NodoAcceso>();
    NodoAcceso acc;
    acc = TipoAcceso();
                         accesos.add(acc);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BRAA:
        ;
        break;
      default:
        jj_la1[32] = jj_gen;
        break label_6;
      }
      acc = TipoAcceso();
                                                                    accesos.add(acc);
    }
      {if (true) return accesos;}
    throw new Error("Missing return statement in function");
  }

  final public NodoAcceso TipoAcceso() throws ParseException {
    Expresion pos;
    Expresion posY;
    if (jj_2_10(4)) {
      jj_consume_token(BRAA);
      pos = Expresion();
      jj_consume_token(BRAC);
                                                                                  {if (true) return new NodoAcceso(pos, true);}
    } else if (jj_2_11(4)) {
      jj_consume_token(BRAA);
      jj_consume_token(BRAA);
      pos = Expresion();
      jj_consume_token(BRAC);
      jj_consume_token(BRAC);
                                                                                  {if (true) return new NodoAcceso(pos, false);}
    } else if (jj_2_12(4)) {
      jj_consume_token(BRAA);
      pos = Expresion();
      jj_consume_token(COMA);
      posY = Expresion();
      jj_consume_token(BRAC);
                                                                                  {if (true) return new NodoAcceso(pos, posY, false, true);}
    } else if (jj_2_13(4)) {
      jj_consume_token(BRAA);
      jj_consume_token(COMA);
      posY = Expresion();
      jj_consume_token(BRAC);
                                                                                  {if (true) return new NodoAcceso(null, posY, false, true);}
    } else if (jj_2_14(4)) {
      jj_consume_token(BRAA);
      pos = Expresion();
      jj_consume_token(COMA);
      jj_consume_token(BRAC);
                                                                                  {if (true) return new NodoAcceso(pos, null, false, true);}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoAst AsignarEstructura() throws ParseException {
    Token t;
    LinkedList<NodoAcceso> accesos;
    Expresion e;
    t = jj_consume_token(IDENTIFICADOR);
    accesos = Accesos();
    jj_consume_token(IGUAL);
    e = Expresion();
      {if (true) return new AsignarEstructura(t.image, accesos, e, token.beginLine, token.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public Expresion Expresion() throws ParseException {
    Expresion e;
    e = ExpresionTernario();
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionTernario() throws ParseException {
    Expresion e, ev, ef;
    e = ExpresionOr();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TERNARIO:
      jj_consume_token(TERNARIO);
      ev = Expresion();
      jj_consume_token(DOSPUNTOS);
      ef = Expresion();
                                                                    e = new Ternario(e, ev, ef, token.beginLine, token.beginColumn);
      break;
    default:
      jj_la1[33] = jj_gen;
      ;
    }
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionOr() throws ParseException {
    Expresion e, e2;
    e = ExpresionAnd();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[34] = jj_gen;
        break label_7;
      }
      jj_consume_token(OR);
      e2 = ExpresionAnd();
                                       e = new Operacion(e, e2, Operacion.getOperador("|"), token.beginLine, token.beginColumn);
    }
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionAnd() throws ParseException {
    Expresion e, e2;
    e = ExpresionIgualdad();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[35] = jj_gen;
        break label_8;
      }
      jj_consume_token(AND);
      e2 = ExpresionIgualdad();
                                              e = new Operacion(e, e2, Operacion.getOperador("&"), token.beginLine, token.beginColumn);
    }
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionIgualdad() throws ParseException {
    Expresion e, e2;
    e = ExpresionRelacional();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IGUALIGUAL:
      case DIFQUE:
        ;
        break;
      default:
        jj_la1[36] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IGUALIGUAL:
        jj_consume_token(IGUALIGUAL);
        e2 = ExpresionRelacional();
                                                      e = new Operacion(e, e2, Operacion.getOperador("=="), token.beginLine, token.beginColumn);
        break;
      case DIFQUE:
        jj_consume_token(DIFQUE);
        e2 = ExpresionRelacional();
                                                      e = new Operacion(e, e2, Operacion.getOperador("!="), token.beginLine, token.beginColumn);
        break;
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionRelacional() throws ParseException {
    Expresion e, e2;
    e = ExpresionAditivas();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MENORQUE:
      case MAYORQUE:
      case MENORIGUAL:
      case MAYORIGUAL:
        ;
        break;
      default:
        jj_la1[38] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAYORQUE:
        jj_consume_token(MAYORQUE);
        e2 = ExpresionAditivas();
                                                          e = new Operacion(e, e2, Operacion.getOperador(">"), token.beginLine, token.beginColumn);
        break;
      case MENORQUE:
        jj_consume_token(MENORQUE);
        e2 = ExpresionAditivas();
                                                          e = new Operacion(e, e2, Operacion.getOperador("<"), token.beginLine, token.beginColumn);
        break;
      case MAYORIGUAL:
        jj_consume_token(MAYORIGUAL);
        e2 = ExpresionAditivas();
                                                          e = new Operacion(e, e2, Operacion.getOperador(">="), token.beginLine, token.beginColumn);
        break;
      case MENORIGUAL:
        jj_consume_token(MENORIGUAL);
        e2 = ExpresionAditivas();
                                                          e = new Operacion(e, e2, Operacion.getOperador("<="), token.beginLine, token.beginColumn);
        break;
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionAditivas() throws ParseException {
    Expresion e, e2;
    e = ExpresionMultiplicativas();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAS:
      case MENOS:
        ;
        break;
      default:
        jj_la1[40] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAS:
        jj_consume_token(MAS);
        e2 = ExpresionMultiplicativas();
                                                      e = new Operacion(e, e2, Operacion.getOperador("+"), token.beginLine, token.beginColumn);
        break;
      case MENOS:
        jj_consume_token(MENOS);
        e2 = ExpresionMultiplicativas();
                                                      e = new Operacion(e, e2, Operacion.getOperador("-"), token.beginLine, token.beginColumn);
        break;
      default:
        jj_la1[41] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionMultiplicativas() throws ParseException {
    Expresion e, e2;
    e = ExpresionExponente();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case POR:
      case DIVIDIDO:
      case MODULO:
        ;
        break;
      default:
        jj_la1[42] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case POR:
        jj_consume_token(POR);
        e2 = ExpresionExponente();
                                                  e = new Operacion(e, e2, Operacion.getOperador("*"), token.beginLine, token.beginColumn);
        break;
      case DIVIDIDO:
        jj_consume_token(DIVIDIDO);
        e2 = ExpresionExponente();
                                                  e = new Operacion(e, e2, Operacion.getOperador("/"), token.beginLine, token.beginColumn);
        break;
      case MODULO:
        jj_consume_token(MODULO);
        e2 = ExpresionExponente();
                                                  e = new Operacion(e, e2, Operacion.getOperador("%%"), token.beginLine, token.beginColumn);
        break;
      default:
        jj_la1[43] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionExponente() throws ParseException {
    Expresion e, e2;
    e = ExpresionUnaria();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case POTENCIA:
        ;
        break;
      default:
        jj_la1[44] = jj_gen;
        break label_13;
      }
      jj_consume_token(POTENCIA);
      e2 = ExpresionUnaria();
                                           e = new Operacion(e, e2, Operacion.getOperador("^"), token.beginLine, token.beginColumn);
    }
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion ExpresionUnaria() throws ParseException {
    Expresion e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MENOS:
      jj_consume_token(MENOS);
      e = ExpresionUnaria();
                                      {if (true) return new Operacion(e, Operacion.Operador.MENOS_UNARIO, token.beginLine, token.beginColumn);}
      break;
    case NOT:
      jj_consume_token(NOT);
      e = ExpresionUnaria();
                                      {if (true) return new Operacion(e, Operacion.getOperador("!"), token.beginLine, token.beginColumn);}
      break;
    case ENTERO:
    case DECIMAL:
    case TRUE:
    case FALSE:
    case NULO:
    case DEFECTO:
    case PARA:
    case IDENTIFICADOR:
    case STRING:
      e = Primitivo();
                                     {if (true) return e;}
      break;
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Expresion Primitivo() throws ParseException {
    Expresion e; Token t; String cad;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ENTERO:
      jj_consume_token(ENTERO);
                          {if (true) return new Primitivo(Integer.parseInt(token.image), "Integer", token.beginLine, token.beginColumn);}
      break;
    case DECIMAL:
      jj_consume_token(DECIMAL);
                          {if (true) return new Primitivo(Double.parseDouble(token.image), "Numeric", token.beginLine, token.beginColumn);}
      break;
    case STRING:
      t = jj_consume_token(STRING);
                            cad = t.image.substring(1,t.image.length()-1);
                            cad = cad.replace("\\","\\");
                            cad = cad.replace("\\n","\n");
                            cad = cad.replace("\\t","\t");
                            {if (true) return new Primitivo(cad, "String", token.beginLine, token.beginColumn);}
      break;
    case TRUE:
      jj_consume_token(TRUE);
                              {if (true) return new Primitivo(true, "Boolean", token.beginLine, token.beginColumn);}
      break;
    case FALSE:
      jj_consume_token(FALSE);
                              {if (true) return new Primitivo(false, "Boolean", token.beginLine, token.beginColumn);}
      break;
    case NULO:
      jj_consume_token(NULO);
                              {if (true) return new Primitivo("null", "String", token.beginLine, token.beginColumn);}
      break;
    case DEFECTO:
      jj_consume_token(DEFECTO);
                              {if (true) return new Defecto(token.beginLine, token.beginColumn);}
      break;
    default:
      jj_la1[46] = jj_gen;
      if (jj_2_15(4)) {
        e = Llamada();
                                      {if (true) return e;}
      } else if (jj_2_16(4)) {
        e = Acceso();
                                          {if (true) return e;}
      } else if (jj_2_17(4)) {
        t = jj_consume_token(IDENTIFICADOR);
                                           {if (true) return new Identificador(t.image, token.beginLine, token.beginColumn);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PARA:
          jj_consume_token(PARA);
          e = Expresion();
          jj_consume_token(PARC);
                                      {if (true) return e;}
          break;
        default:
          jj_la1[47] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_3R_29() {
    if (jj_3R_32()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(IGUAL)) return true;
    if (jj_scan_token(PARA)) return true;
    if (jj_3R_24()) return true;
    if (jj_scan_token(PARC)) return true;
    if (jj_scan_token(FLECHA)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(PARA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_20()) jj_scanpos = xsp;
    if (jj_scan_token(PARC)) return true;
    xsp = jj_scanpos;
    if (jj_3R_22()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) return true;
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(IGUAL)) return true;
    if (jj_scan_token(FUNCTION)) return true;
    if (jj_scan_token(PARA)) return true;
    if (jj_3R_24()) return true;
    if (jj_scan_token(PARC)) return true;
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_scan_token(PARA)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(PARC)) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_scan_token(DEFECTO)) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_scan_token(NULO)) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(DECIMAL)) return true;
    return false;
  }

  private boolean jj_3R_61() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(ENTERO)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_3R_61()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(MENOS)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(POTENCIA)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_3R_53()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_54()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(MODULO)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(DIVIDIDO)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(POR)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_49()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_50()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(MENOS)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(MAS)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_43()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_44()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(MENORIGUAL)) return true;
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(MAYORIGUAL)) return true;
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(MENORQUE)) return true;
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(MAYORQUE)) return true;
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_3R_39()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_40()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(DIFQUE)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(SINO)) return true;
    if (jj_scan_token(LLAVEA)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) return true;
    }
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(IGUALIGUAL)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_scan_token(SINO)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_38()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(SI)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_34()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(IGUAL)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(COMA)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(TERNARIO)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(COMA)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(IGUAL)) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_scan_token(BRAA)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(COMA)) return true;
    if (jj_scan_token(BRAC)) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(BRAA)) return true;
    if (jj_scan_token(COMA)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(BRAC)) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_scan_token(BRAA)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(COMA)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(BRAA)) return true;
    if (jj_scan_token(BRAA)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(BRAC)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_10() {
    if (jj_scan_token(BRAA)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(BRAC)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_18()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_27()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_28()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public GramaticaJCCTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[48];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x33c8600,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x33c8600,0x0,0x0,0x0,0x0,0x33c8600,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x33c8600,0x0,0x800,0x20000,0x10000,0x8000000,0x0,0x8027180,0x20000000,0x20000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8027180,0x27180,0x8000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x200000,0x200,0x200,0x200,0x200,0x200,0x200,0x200,0x200,0x0,0x200000,0x20000,0x200000,0x400,0x200000,0x200,0x200,0x200,0x200,0x200,0x200,0x200,0x200,0x0,0x200000,0x0,0x0,0x0,0x0,0x20000,0x1300004,0x0,0x0,0x80,0x80000,0x40000,0x18000,0x18000,0x7800,0x7800,0x6,0x6,0x58,0x58,0x20,0x1300004,0x1000000,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[17];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public GramaticaJCC(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GramaticaJCC(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GramaticaJCCTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public GramaticaJCC(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GramaticaJCCTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public GramaticaJCC(GramaticaJCCTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GramaticaJCCTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[57];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 48; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 57; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 17; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
