/* Generated By:JavaCC: Do not edit this line. GramaticaJCCConstants.java */
package Arit.AnalizadorJCC;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaJCCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTERO = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int IMPRIMIR = 9;
  /** RegularExpression Id. */
  int SI = 10;
  /** RegularExpression Id. */
  int SINO = 11;
  /** RegularExpression Id. */
  int TRUE = 12;
  /** RegularExpression Id. */
  int FALSE = 13;
  /** RegularExpression Id. */
  int NULO = 14;
  /** RegularExpression Id. */
  int SWITCH = 15;
  /** RegularExpression Id. */
  int CASE = 16;
  /** RegularExpression Id. */
  int DEFECTO = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int BREAK = 19;
  /** RegularExpression Id. */
  int CONTINUE = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int FUNCTION = 22;
  /** RegularExpression Id. */
  int FLECHA = 23;
  /** RegularExpression Id. */
  int DO = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int IN = 26;
  /** RegularExpression Id. */
  int PARA = 27;
  /** RegularExpression Id. */
  int PARC = 28;
  /** RegularExpression Id. */
  int BRAA = 29;
  /** RegularExpression Id. */
  int BRAC = 30;
  /** RegularExpression Id. */
  int LLAVEA = 31;
  /** RegularExpression Id. */
  int LLAVEC = 32;
  /** RegularExpression Id. */
  int MAS = 33;
  /** RegularExpression Id. */
  int MENOS = 34;
  /** RegularExpression Id. */
  int POR = 35;
  /** RegularExpression Id. */
  int DIVIDIDO = 36;
  /** RegularExpression Id. */
  int POTENCIA = 37;
  /** RegularExpression Id. */
  int MODULO = 38;
  /** RegularExpression Id. */
  int TERNARIO = 39;
  /** RegularExpression Id. */
  int DOSPUNTOS = 40;
  /** RegularExpression Id. */
  int PTCOMA = 41;
  /** RegularExpression Id. */
  int IGUAL = 42;
  /** RegularExpression Id. */
  int MENORQUE = 43;
  /** RegularExpression Id. */
  int MAYORQUE = 44;
  /** RegularExpression Id. */
  int MENORIGUAL = 45;
  /** RegularExpression Id. */
  int MAYORIGUAL = 46;
  /** RegularExpression Id. */
  int IGUALIGUAL = 47;
  /** RegularExpression Id. */
  int DIFQUE = 48;
  /** RegularExpression Id. */
  int COMA = 49;
  /** RegularExpression Id. */
  int AND = 50;
  /** RegularExpression Id. */
  int OR = 51;
  /** RegularExpression Id. */
  int NOT = 52;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 53;
  /** RegularExpression Id. */
  int STRING = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<ENTERO>",
    "<DECIMAL>",
    "\"Print\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"while\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"function\"",
    "\"=>\"",
    "\"do\"",
    "\"for\"",
    "\"in\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"%%\"",
    "\"?\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\",\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<token of kind 55>",
    "\"\\\"\"",
  };

}
