/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AritIDE;

import Arit.Analizador;
import AritIDE.Editor.Editor;
import Error.ReporteErrores;
import Reportes.ReporteTabla;
import java.awt.Dimension;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ddani
 */
public class AritIDE extends javax.swing.JFrame {

    /**
     * Creates new form AritIDE
     */
    public AritIDE() {
        initComponents();
        Informacion.Informacion.setUp(Consola);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CupFlex = new javax.swing.JButton();
        EditorTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        inicioJCC = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        GuardarComo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        ReporteTabla = new javax.swing.JMenuItem();
        ReporteAst = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        NuevaPes = new javax.swing.JMenuItem();
        CerrarPestaña = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arit IDE - 201503935");

        CupFlex.setText("Iniciar");
        CupFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CupFlexActionPerformed(evt);
            }
        });

        Consola.setColumns(20);
        Consola.setRows(5);
        jScrollPane1.setViewportView(Consola);

        jLabel1.setText("Consola");

        inicioJCC.setText("Inicio JCC");
        inicioJCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioJCCActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jMenu1.add(Abrir);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jMenu1.add(Guardar);

        GuardarComo.setText("Guardar Como");
        GuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(GuardarComo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");

        jMenuItem5.setText("Reporte de Errores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        ReporteTabla.setText("Reporte Tabla Simbolos");
        ReporteTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteTablaActionPerformed(evt);
            }
        });
        jMenu2.add(ReporteTabla);

        ReporteAst.setText("Reporte Ast");
        ReporteAst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteAstActionPerformed(evt);
            }
        });
        jMenu2.add(ReporteAst);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pestaña");

        NuevaPes.setText("Nueva Pestaña");
        NuevaPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaPesActionPerformed(evt);
            }
        });
        jMenu3.add(NuevaPes);

        CerrarPestaña.setText("Cerrar Pestaña");
        CerrarPestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarPestañaActionPerformed(evt);
            }
        });
        jMenu3.add(CerrarPestaña);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CupFlex)
                        .addGap(41, 41, 41)
                        .addComponent(inicioJCC))
                    .addComponent(jLabel1)
                    .addComponent(EditorTab)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CupFlex)
                    .addComponent(inicioJCC))
                .addGap(18, 18, 18)
                .addComponent(EditorTab, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReporteTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteTablaActionPerformed
        // TODO add your handling code here:
        ReporteTabla repo = new ReporteTabla(Informacion.Informacion.simbolos);
        repo.escribirReporte();
    }//GEN-LAST:event_ReporteTablaActionPerformed

    private void NuevaPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaPesActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingrese nombre de la pestaña");
        Editor txt = new Editor("..\\" + nombre, nombre);
        txt.pathArchivo = "";
        this.EditorTab.addTab(txt.getFileName(), txt);
        txt.setPreferredSize(new Dimension(txt.getWidth(), 1000));
    }//GEN-LAST:event_NuevaPesActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        File arch = fileChooser.getSelectedFile();
        if (arch != null) {
            String ruta = fileChooser.getSelectedFile().getPath();

            if (!ruta.equals("")) {

                String nombre = fileChooser.getSelectedFile().getName();
                Editor txt = new Editor(ruta, nombre);
                this.EditorTab.addTab(txt.getFileName(), txt);
                txt.ReadFile();
                txt.setPreferredSize(new Dimension(txt.getWidth(), 100));
            } else {
                JOptionPane.showMessageDialog(this, "No Existe un Archivo Seleccionado!", "Error: Abrir Archivo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ReporteErrores repE = new ReporteErrores(Informacion.Informacion.errores);
        repE.GenearReporte();;
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void CupFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CupFlexActionPerformed
        // TODO add your handling code here:
        Object c = EditorTab.getSelectedComponent();
        if (c instanceof Editor) {
            Editor aux = (Editor) c;

            Analizador an = new Analizador(aux.areaEdicion.getText());
            an.Analizar();
        }
    }//GEN-LAST:event_CupFlexActionPerformed

    private void inicioJCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioJCCActionPerformed
        // TODO add your handling code here:
        Object c = EditorTab.getSelectedComponent();
        if (c instanceof Editor) {
            Editor aux = (Editor) c;

            Analizador an = new Analizador(aux.areaEdicion.getText());
            an.AnalizarJCC();
        }
    }//GEN-LAST:event_inicioJCCActionPerformed

    private void CerrarPestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarPestañaActionPerformed
        // TODO add your handling code here:
        EditorTab.remove(EditorTab.getSelectedComponent());
    }//GEN-LAST:event_CerrarPestañaActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        Object c = EditorTab.getSelectedComponent();
        if (c instanceof Editor) {
            Editor aux = (Editor) c;
            if (!aux.pathArchivo.equals("")) {
                if (aux.saveFile()) {
                    JOptionPane.showMessageDialog(null, "Se guardo el archivo ");
                } else {
                    JOptionPane.showMessageDialog(null, "No se guardo el archivo ");
                }
            } else {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                fileChooser.showOpenDialog(fileChooser);
                File arch = fileChooser.getSelectedFile();
                if (arch != null) {
                    String ruta = arch.getPath() + "\\" + aux.getFileName();
                    aux.pathArchivo = ruta;
                    System.out.println(ruta);
                    aux.saveFile();
                }
            }

        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void GuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarComoActionPerformed
        // TODO add your handling code here:
        Object c = EditorTab.getSelectedComponent();
        if (c instanceof Editor) {
            Editor aux = (Editor) c;
            String nombre = JOptionPane.showInputDialog("Ingresar nombre del archivo");
            if (nombre != "") {
                aux.setFileName(nombre+".arit");
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                fileChooser.showOpenDialog(fileChooser);
                File arch = fileChooser.getSelectedFile();
                if (arch != null) {
                    String ruta = arch.getPath() + "\\" + aux.getFileName();
                    aux.pathArchivo = ruta;
                    System.out.println(ruta);
                    aux.saveFile();
                }
            }
        }
    }//GEN-LAST:event_GuardarComoActionPerformed

    private void ReporteAstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteAstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteAstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AritIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AritIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AritIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AritIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AritIDE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenuItem CerrarPestaña;
    private javax.swing.JTextArea Consola;
    private javax.swing.JButton CupFlex;
    private javax.swing.JTabbedPane EditorTab;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem GuardarComo;
    private javax.swing.JMenuItem NuevaPes;
    private javax.swing.JMenuItem ReporteAst;
    private javax.swing.JMenuItem ReporteTabla;
    private javax.swing.JButton inicioJCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
