/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AritIDE.Editor;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.Theme;
import org.fife.ui.rsyntaxtextarea.TokenMakerFactory;
import org.fife.ui.rsyntaxtextarea.folding.CurlyFoldParser;
import org.fife.ui.rsyntaxtextarea.folding.FoldParserManager;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author ddani
 */
public class Editor extends javax.swing.JPanel {

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
    }

    public RSyntaxTextArea areaEdicion;
    public String pathArchivo;
    public String fileExtension = "";
    public String pathcambiada;
    String fileName;
    public String nom;
    
    public Editor(String pathArchivo, String nombre) {
        this.pathArchivo = pathArchivo;
        initComponents();

        this.fileName = nombre;
        try {
            String aux[] = this.fileName.split("\\.");
            this.fileExtension = aux[1];
            //System.out.println(pathArchivo);
            String prueba = pathArchivo;
            String nuevo = prueba.replace("\\"+this.fileName, "");
            //System.out.println("---"+nuevo);
            this.pathcambiada = nuevo;
            nom = aux[0];
        } catch (Exception e) {

        }
        
        FoldParserManager.get().addFoldParserMapping("text/fs", new CurlyFoldParser());
        FoldParserManager.get().addFoldParserMapping("text/gxml", new CurlyFoldParser());

        //System.out.println(this.fileName);

        this.setLayout(new BorderLayout());
        RSyntaxTextArea t = new RSyntaxTextArea();
        this.areaEdicion = t;
        t.setCodeFoldingEnabled(true);
        colocaColorSyntaxis(t, fileExtension);
        RTextScrollPane sp = new RTextScrollPane(t);
        this.add(sp);
    }
    
    private void colocaColorSyntaxis(RSyntaxTextArea editor, String ext) {
        AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory) TokenMakerFactory.getDefaultInstance();
        atmf.putMapping("text/gxml", "AritIDE.Editor.Arit.AritSintax");
        editor.setSyntaxEditingStyle("text/gxml");
        try {
            Theme theme = Theme.load(getClass().getResourceAsStream("/AritIDE/Editor/Arit/Tema.xml"));
            theme.apply(editor);
        } catch (Exception e) {
        } 
    }
    
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public void ReadFile() {
        try {
            FileReader file = new FileReader(this.pathArchivo);
            BufferedReader reader = new BufferedReader(file);
            String text = "";
            String line = reader.readLine();
            while (line != null) {
                text += line + "\n";
                line = reader.readLine();
            }
            this.areaEdicion.setText(text);
            reader.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Error: " + e.getMessage(), "Error Al Abrir el archivo", JOptionPane.ERROR_MESSAGE);
        }
    }

    public String readText() {
        try {
            FileReader file = new FileReader(this.pathArchivo);
            BufferedReader reader = new BufferedReader(file);
            String text = "";
            String line = reader.readLine();
            while (line != null) {
                text += line + "\n";
                line = reader.readLine();
            }
            return text;
        } catch (Exception e) {
        }
        return "";
    }
    
    public Boolean saveFile() {
        File f = new File(this.pathArchivo);
        try {
            String text = this.areaEdicion.getText();
            BufferedWriter writer = new BufferedWriter(new FileWriter(f));
            writer.write(text);
            writer.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar archivo: " + this.pathArchivo + " | " + e.getMessage());
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
